services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gisapply}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gisapply-password}
      POSTGRES_DB: ${POSTGRES_DB:-gisapply}
    #volumes:
    #  - db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT:-18080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USERNAME: ${POSTGRES_USER:-gisapply}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-gisapply-password}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-dracula}
      ADMINER_PLUGINS: ${ADMINER_PLUGINS:-tables-filter tinymce}

  minio:
    image: bitnamilegacy/minio:latest
    #volumes:
    #  - minio:/bitnami/minio/data
    ports:
      - ${MINIO_PORT:-19000}:9000
      - ${MINIO_PORT_INTERNAL:-9001}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
      MINIO_BROWSER_SESSION_DURATION: ${MINIO_BROWSER_SESSION_DURATION:-7d}
      MINIO_BROWSER_LOGIN_ANIMATION: ${MINIO_BROWSER_LOGIN_ANIMATION:-off}

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Berlin
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - '8080:1080'
      - '8025:1025'

  migrations:
    build:
      context: ./
      dockerfile: companions/migrations/Dockerfile
    environment:
      DATABASE_URL: "postgresql://gisapply:gisapply-password@postgres:5432/gisapply?schema=public"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://gisapply:gisapply-password@postgres:5432/gisapply?schema=public"
      REDIS_URL: "redis://redis:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://tracking:4318"
      S3_ENDPOINT: minio
    depends_on:
      - postgres
      - adminer
      - migrations
      - minio
  