apiVersion: v2
name: gis-lms-backend
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "2025.03.20"

dependencies:
  - name: app-template
    repository: https://bjw-s.github.io/helm-charts
    version: "3.6.1"
    alias: app